export const GET_QUOTE = "GET_USERS";
export const QUOTE_ERROR = "USERS_ERROR";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const USER_INPUT_INFO = "USER_INPUT_INFO";
export const GET_COUNTRY_INFO = "GET_CURRENCY";
export const GET_COUNTRY_INFO_ERROR = "GET_CURRENCY_ERROR";
